name: navigation_history_observer
description: A Flutter NavigatorObserver that stores a collection of pushed routes history, as well as the popped history.
version: 1.0.3
homepage: https://github.com/Polarts/navigation_history_observer

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^4.3.2

dev_dependencies:

flutter: